In [17]:
import pandas as pd
import re

In [18]:
 df = pd.read_csv("base_vin_final_temps.csv")
 df_image = pd.read_csv("URLimages.csv")

In [19]:
df.head()

,Unnamed: 0,nom,desc,accroche,visuel,producteur,contenance,deg_alcool,pays,region,...,caractere,couleur,temp_serv,type_produit,bio,prix,reco1,reco2,reco3,reco4
0,0,Le Bal des Papillons 2024 - Horgelus,Élaborée avec soin dans le respect des traditi...,Plongez dans un univers de légèreté et délégan...,95769-fine_default/le-bal-des-papillons-2024-h...,Horgelus,0.75,11.0,France,Sud-Ouest,...,"Blanc Demi-sec, moelleux et liquoreux",Blanc,8-10°C,Vin,NaN,8.6,Colombard-Sauvignon 2024 - Horgelus,N°3 - Colombard-Sauvignon Blanc 2024 - UBY,Gros-Manseng & Sauvignon 2024 - Horgelus,N°2 - Chardonnay - Chenin Blanc 2024 - UBY
1,1,Lupo Meraviglia Tre di Tre 2022 - Botter,"Historiquement, la vinification dans les Pouil...",Une étoile montante des Pouilles vinifiée selo...,80831-fine_default/lupo-meraviglia-tre-di-tre-...,Botter,0.75,14.5,Italie,Pouilles,...,Rouge Charnu et fruité,Rouge,16-18°C,Vin,NaN,10.9,Château Moulin Bellegrave 2022,Narassa 2022 - Domaine Lafage,Crozes-Hermitage - Nobles Rives 2022 - Cave de...,Château Beaumont - Les Pierrières 2022
2,2,Colombard-Sauvignon 2024 - Horgelus,L'harmonieux mariage du colombard et du sauvig...,Savoureux mariage du colombard et du sauvignon...,94492-fine_default/colombard-sauvignon-2024-ho...,Horgelus,0.75,11.5,France,Sud-Ouest,...,Blanc Sec souple et fruité,Blanc,10°C,Vin,NaN,6.6,Le Bal des Papillons 2024 - Horgelus,N°3 - Colombard-Sauvignon Blanc 2024 - UBY,Gros-Manseng & Sauvignon 2024 - Horgelus,N°2 - Chardonnay - Chenin Blanc 2024 - UBY
3,3,N°3 - Colombard-Sauvignon Blanc 2024 - UBY,Léger et fruité ! Ce vin blanc aux arômes d'ag...,La référence incontestable des Côtes de Gascog...,98180-fine_default/n3-colombard-sauvignon-blan...,UBY,0.75,11.0,France,Sud-Ouest,...,NaN,Blanc,10-12°C,Vin,NaN,6.5,Colombard-Sauvignon 2024 - Horgelus,Le Bal des Papillons 2024 - Horgelus,Gros-Manseng & Sauvignon 2024 - Horgelus,N°2 - Chardonnay - Chenin Blanc 2024 - UBY
4,4,Rosé 2024 - Horgelus,"C'est un vin savoureux, séduisant à 100 . Frui...",Découvrez un rosé des plus gourmands au rappor...,95662-fine_default/rose-2024-horgelus.png,Horgelus,0.75,11.5,France,Sud-Ouest,...,Rosé d'apéritif,Rosé,10°C,Vin,NaN,6.2,Dune Gris 2024,Bandol - Les Adrets Rosé 2024 - Moulin de la R...,Les Pieds dans l'Eau 2024 - Alma Cersius,Miraflors 2024 - Domaine Lafage

In [20]:
df_image.head()

   ID                                                URL NomFichier
0   0  https://www.vinatis.com/95769-fine_default/le-...  00000.png
1   1  https://www.vinatis.com/80831-fine_default/lup...  00001.png
2   2  https://www.vinatis.com/94492-fine_default/col...  00002.png
3   3  https://www.vinatis.com/98180-fine_default/n3-...  00003.png
4   4  https://www.vinatis.com/95662-fine_default/ros...  00004.png

In [27]:
import re

def extract_id_visuel_url(url):
    if isinstance(url, str):
        match = re.search(r'(\d+)-', url)
        if match:
            return match.group(1)
    return None

df_image['id_visuel'] = df_image['URL'].apply(extract_id_visuel_url)

In [29]:
import re

def extract_id_visuel(visuel):
    if isinstance(visuel, str):
        match = re.search(r'(\d+)-', visuel)
        if match:
            return match.group(1)
    return None

df['id_visuel'] = df['visuel'].apply(extract_id_visuel)

In [30]:
print(df[['visuel', 'id_visuel']].head())
print(df_image[['URL', 'id_visuel']].head())

                                              visuel id_visuel
0  95769-fine_default/le-bal-des-papillons-2024-h...     95769
1  80831-fine_default/lupo-meraviglia-tre-di-tre-...     80831
2  94492-fine_default/colombard-sauvignon-2024-ho...     94492
3  98180-fine_default/n3-colombard-sauvignon-blan...     98180
4          95662-fine_default/rose-2024-horgelus.png     95662
                                                 URL id_visuel
0  https://www.vinatis.com/95769-fine_default/le-...     95769
1  https://www.vinatis.com/80831-fine_default/lup...     80831
2  https://www.vinatis.com/94492-fine_default/col...     94492
3  https://www.vinatis.com/98180-fine_default/n3-...     98180
4  https://www.vinatis.com/95662-fine_default/ros...     95662

In [38]:
df = df.merge(
    df_image[['id_visuel', 'NomFichier']],
    on='id_visuel',
    how='left'  # ou 'inner' si tu veux garder uniquement les correspondances
)

In [40]:
print(df[['visuel', 'id_visuel', 'NomFichier']].head())

                                              visuel id_visuel NomFichier
0  95769-fine_default/le-bal-des-papillons-2024-h...     95769  00000.png
1  80831-fine_default/lupo-meraviglia-tre-di-tre-...     80831  00001.png
2  94492-fine_default/colombard-sauvignon-2024-ho...     94492  00002.png
3  98180-fine_default/n3-colombard-sauvignon-blan...     98180  00003.png
4          95662-fine_default/rose-2024-horgelus.png     95662  00004.png

In [41]:
df.to_csv("base_vin_final.csv")