In [24]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [25]:
df= pd.read_csv("../../data/process/base_vin_v1.csv")
df.head()

C:\Users\116_9\AppData\Local\Temp\ipykernel_31740\201964840.py:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv("../../data/process/base_vin_v1.csv")

,Unnamed: 0,nom,desc,accroche,visuel,producteur,contenance,deg_alcool,pays,region,...,millesime_1969,millesime_2004,millesime_2007,millesime_2011,millesime_2003,millesime_2005,millesime_1979,millesime_2000,millesime_1995,bio_bool
0,0,Le Bal des Papillons 2024 - Horgelus,Élaborée avec soin dans le respect des traditi...,Plongez dans un univers de légèreté et délégan...,95769-fine_default/le-bal-des-papillons-2024-h...,Horgelus,0.75,11.0,France,Sud-Ouest,...,0,0,0,0,0,0,0,0,0,0
1,1,Lupo Meraviglia Tre di Tre 2022 - Botter,"Historiquement, la vinification dans les Pouil...",Une étoile montante des Pouilles vinifiée selo...,80831-fine_default/lupo-meraviglia-tre-di-tre-...,Botter,0.75,14.5,Italie,Pouilles,...,0,0,0,0,0,0,0,0,0,0
2,2,Colombard-Sauvignon 2024 - Horgelus,L'harmonieux mariage du colombard et du sauvig...,Savoureux mariage du colombard et du sauvignon...,94492-fine_default/colombard-sauvignon-2024-ho...,Horgelus,0.75,11.5,France,Sud-Ouest,...,0,0,0,0,0,0,0,0,0,0
3,3,N°3 - Colombard-Sauvignon Blanc 2024 - UBY,Léger et fruité ! Ce vin blanc aux arômes d'ag...,La référence incontestable des Côtes de Gascog...,98180-fine_default/n3-colombard-sauvignon-blan...,UBY,0.75,11.0,France,Sud-Ouest,...,0,0,0,0,0,0,0,0,0,0
4,4,Rosé 2024 - Horgelus,"C'est un vin savoureux, séduisant à 100 . Frui...",Découvrez un rosé des plus gourmands au rappor...,95662-fine_default/rose-2024-horgelus.png,Horgelus,0.75,11.5,France,Sud-Ouest,...,0,0,0,0,0,0,0,0,0,0

In [26]:
list(df.columns)

['Unnamed: 0',
 'nom',
 'desc',
 'accroche',
 'visuel',
 'producteur',
 'contenance',
 'deg_alcool',
 'pays',
 'region',
 'appellation',
 'cepages',
 'millesime',
 'accords',
 'gout',
 'caractere',
 'couleur',
 'temp_serv',
 'type_produit',
 'bio',
 'prix',
 'accord_aperitif',
 'accord_barbecue',
 'accord_champignon',
 'accord_charcuterie',
 'accord_charcuterie_corse',
 'accord_coquillage_et_crustace',
 'accord_cuisine_du_monde',
 'accord_dessert_chocolate',
 'accord_dessert_fruite',
 'accord_digestif',
 'accord_entree',
 'accord_foie_gras',
 'accord_fromage',
 'accord_gambas_flambees',
 'accord_gibier',
 'accord_pave_de_turbot_cuit_au_beurre_sale_et_aux_salicornes',
 'accord_poisson',
 'accord_risotto_aux_asperges.',
 'accord_viande_blanche',
 'accord_viande_rouge',
 'accord_viandes_blanches',
 'accord_viandes_rouges',
 'accord_volaille',
 'accord_blanches',
 'accord_fromages.',
 'accord_gibiers',
 'accord_grillades',
 'accord_viandes',
 'accord_volailles',
 'caract_blanc_demi-sec',
 'caract_blanc_sec_ample_et_race',
 'caract_blanc_sec_leger_et_nerveux',
 'caract_blanc_sec_souple_et_fruite',
 'caract_blanc_sec_tres_aromatique',
 'caract_blanc_vin_de_maceration',
 'caract_floral',
 'caract_fruite_agrumes',
 'caract_fruite_fruits_blancs',
 'caract_mineral',
 'caract_orange_fruite_et_fin',
 "caract_rose_d'aperitif",
 'caract_rose_de_gastronomie',
 'caract_rose_de_repas',
 'caract_rouge_charnu_et_fruite',
 'caract_rouge_complexe',
 'caract_rouge_elegant_et_race',
 'caract_rouge_leger_et_fruite',
 'caract_rouge_puissant_et_genereux',
 'caract_rouge_tannique_et_race',
 'caract_vin_doux_naturel_et_de_liqueur',
 'caract_vin_effervescent',
 'caract_moelleux_et_liquoreux',
 'caract_tannique_et_race',
 'cepages_trouves',
 'cepage_agiorgitiko',
 'cepage_aglianico',
 'cepage_albarino',
 'cepage_albariño',
 'cepage_aligote',
 'cepage_altesse',
 'cepage_arinto',
 'cepage_auxerrois',
 'cepage_baga',
 'cepage_barbera',
 'cepage_baroque',
 'cepage_bobal',
 'cepage_braucol',
 'cepage_cabernet_franc',
 'cepage_cabernet_sauvignon',
 'cepage_carcaghjolu',
 'cepage_carignan',
 'cepage_carmenere',
 'cepage_carricante',
 'cepage_chardonnay',
 'cepage_chasselas',
 'cepage_chenin',
 'cepage_chenin_blanc',
 'cepage_cinsault',
 'cepage_clairette',
 'cepage_colombard',
 'cepage_corvina',
 'cepage_corvinone',
 'cepage_counoise',
 'cepage_dolcetto',
 'cepage_falanghina',
 'cepage_fer_servadou',
 'cepage_fiano',
 'cepage_folle_blanche',
 'cepage_frappato',
 'cepage_furmint',
 'cepage_gamay',
 'cepage_garnacha',
 'cepage_gewurztraminer',
 'cepage_godello',
 'cepage_graciano',
 'cepage_greco',
 'cepage_grenache',
 'cepage_grillo',
 'cepage_grolleau',
 'cepage_gros_manseng',
 'cepage_gruner_veltliner',
 'cepage_hárslevelű',
 'cepage_inzolia',
 'cepage_jacquere',
 'cepage_lambrusco',
 'cepage_listán_negro',
 'cepage_loureira',
 'cepage_loureiro',
 'cepage_macabeo',
 'cepage_macabeu',
 'cepage_malbec',
 'cepage_malvasia',
 'cepage_marsanne',
 'cepage_mataro',
 'cepage_mauzac',
 'cepage_mazuelo',
 'cepage_melon_de_bourgogne',
 'cepage_mencia',
 'cepage_merlot',
 'cepage_monastrell',
 'cepage_mondeuse',
 'cepage_montepulciano',
 'cepage_moscato',
 'cepage_mourvedre',
 'cepage_muscat',
 'cepage_nebbiolo',
 'cepage_negroamaro',
 'cepage_nerello_mascalese',
 'cepage_nero_davola',
 'cepage_nielluccio',
 'cepage_niellucciu',
 'cepage_obaideh',
 'cepage_petit_courbu',
 'cepage_petit_manseng',
 'cepage_petit_verdot',
 'cepage_pineau_daunis',
 'cepage_pinot_blanc',
 'cepage_pinot_grigio',
 'cepage_pinot_gris',
 'cepage_pinot_noir',
 'cepage_pinotage',
 'cepage_piquepoul',
 'cepage_poulsard',
 'cepage_primitivo',
 'cepage_riesling',
 'cepage_rkatsiteli',
 'cepage_romorantin',
 'cepage_roussanne',
 'cepage_sangiovese',
 'cepage_saperavi',
 'cepage_sauvignon_blanc',
 'cepage_savagnin',
 'cepage_sciaccarellu',
 'cepage_semillon',
 'cepage_shiraz',
 'cepage_soave',
 'cepage_sylvaner',
 'cepage_syrah',
 'cepage_tannat',
 'cepage_tempranillo',
 'cepage_terret',
 'cepage_tibouren',
 'cepage_torrontes',
 'cepage_trebbiano',
 'cepage_trousseau',
 'cepage_ugni_blanc',
 'cepage_vermentino',
 'cepage_viognier',
 'cepage_viura',
 'cepage_xarel_lo',
 'cepage_zinfandel',
 'type_accessoire',
 'type_effervescent',
 'type_vin',
 'couleur_blanc',
 'couleur_rouge',
 'couleur_rose',
 'couleur_orange',
 'couleur_ambre',
 'couleur_rubis',
 'prix_std',
 'degres_std',
 'pays_afrique_du_sud',
 'pays_allemagne',
 'pays_angleterre',
 'pays_argentine',
 'pays_armenie',
 'pays_australie',
 'pays_autriche',
 'pays_bulgarie',
 'pays_chili',
 'pays_chine',
 'pays_croatie',
 'pays_espagne',
 'pays_etats_unis',
 'pays_france',
 'pays_grece',
 'pays_georgie',
 'pays_hongrie',
 'pays_italie',
 'pays_liban',
 'pays_maroc',
 'pays_mexique',
 'pays_moldavie',
 'pays_nouvelle_zelande',
 'pays_plateau_du_golan',
 'pays_portugal',
 'pays_perou',
 'pays_roumanie',
 'pays_slovenie',
 'pays_suisse',
 'pays_turquie',
 'pays_uruguay',
 'millesime_2024',
 'millesime_2022',
 'millesime_2023',
 'millesime_2020',
 'millesime_2019',
 'millesime_2015',
 'millesime_2021',
 'millesime_2017',
 'millesime_2016',
 'millesime_2018',
 'millesime_non millésimé',
 'millesime_2010',
 'millesime_2012',
 'millesime_2014',
 'millesime_1980',
 'millesime_1998',
 'millesime_2013',
 'millesime_1959',
 'millesime_1974',
 'millesime_2001',
 'millesime_2009',
 'millesime_2008',
 'millesime_1989',
 'millesime_1969',
 'millesime_2004',
 'millesime_2007',
 'millesime_2011',
 'millesime_2003',
 'millesime_2005',
 'millesime_1979',
 'millesime_2000',
 'millesime_1995',
 'bio_bool']

In [27]:
# Renvoie une Series où chaque valeur est le nom d’une colonne
print(df.columns.tolist())

['Unnamed: 0', 'nom', 'desc', 'accroche', 'visuel', 'producteur', 'contenance', 'deg_alcool', 'pays', 'region', 'appellation', 'cepages', 'millesime', 'accords', 'gout', 'caractere', 'couleur', 'temp_serv', 'type_produit', 'bio', 'prix', 'accord_aperitif', 'accord_barbecue', 'accord_champignon', 'accord_charcuterie', 'accord_charcuterie_corse', 'accord_coquillage_et_crustace', 'accord_cuisine_du_monde', 'accord_dessert_chocolate', 'accord_dessert_fruite', 'accord_digestif', 'accord_entree', 'accord_foie_gras', 'accord_fromage', 'accord_gambas_flambees', 'accord_gibier', 'accord_pave_de_turbot_cuit_au_beurre_sale_et_aux_salicornes', 'accord_poisson', 'accord_risotto_aux_asperges.', 'accord_viande_blanche', 'accord_viande_rouge', 'accord_viandes_blanches', 'accord_viandes_rouges', 'accord_volaille', 'accord_blanches', 'accord_fromages.', 'accord_gibiers', 'accord_grillades', 'accord_viandes', 'accord_volailles', 'caract_blanc_demi-sec', 'caract_blanc_sec_ample_et_race', 'caract_blanc_sec_leger_et_nerveux', 'caract_blanc_sec_souple_et_fruite', 'caract_blanc_sec_tres_aromatique', 'caract_blanc_vin_de_maceration', 'caract_floral', 'caract_fruite_agrumes', 'caract_fruite_fruits_blancs', 'caract_mineral', 'caract_orange_fruite_et_fin', "caract_rose_d'aperitif", 'caract_rose_de_gastronomie', 'caract_rose_de_repas', 'caract_rouge_charnu_et_fruite', 'caract_rouge_complexe', 'caract_rouge_elegant_et_race', 'caract_rouge_leger_et_fruite', 'caract_rouge_puissant_et_genereux', 'caract_rouge_tannique_et_race', 'caract_vin_doux_naturel_et_de_liqueur', 'caract_vin_effervescent', 'caract_moelleux_et_liquoreux', 'caract_tannique_et_race', 'cepages_trouves', 'cepage_agiorgitiko', 'cepage_aglianico', 'cepage_albarino', 'cepage_albariño', 'cepage_aligote', 'cepage_altesse', 'cepage_arinto', 'cepage_auxerrois', 'cepage_baga', 'cepage_barbera', 'cepage_baroque', 'cepage_bobal', 'cepage_braucol', 'cepage_cabernet_franc', 'cepage_cabernet_sauvignon', 'cepage_carcaghjolu', 'cepage_carignan', 'cepage_carmenere', 'cepage_carricante', 'cepage_chardonnay', 'cepage_chasselas', 'cepage_chenin', 'cepage_chenin_blanc', 'cepage_cinsault', 'cepage_clairette', 'cepage_colombard', 'cepage_corvina', 'cepage_corvinone', 'cepage_counoise', 'cepage_dolcetto', 'cepage_falanghina', 'cepage_fer_servadou', 'cepage_fiano', 'cepage_folle_blanche', 'cepage_frappato', 'cepage_furmint', 'cepage_gamay', 'cepage_garnacha', 'cepage_gewurztraminer', 'cepage_godello', 'cepage_graciano', 'cepage_greco', 'cepage_grenache', 'cepage_grillo', 'cepage_grolleau', 'cepage_gros_manseng', 'cepage_gruner_veltliner', 'cepage_hárslevelű', 'cepage_inzolia', 'cepage_jacquere', 'cepage_lambrusco', 'cepage_listán_negro', 'cepage_loureira', 'cepage_loureiro', 'cepage_macabeo', 'cepage_macabeu', 'cepage_malbec', 'cepage_malvasia', 'cepage_marsanne', 'cepage_mataro', 'cepage_mauzac', 'cepage_mazuelo', 'cepage_melon_de_bourgogne', 'cepage_mencia', 'cepage_merlot', 'cepage_monastrell', 'cepage_mondeuse', 'cepage_montepulciano', 'cepage_moscato', 'cepage_mourvedre', 'cepage_muscat', 'cepage_nebbiolo', 'cepage_negroamaro', 'cepage_nerello_mascalese', 'cepage_nero_davola', 'cepage_nielluccio', 'cepage_niellucciu', 'cepage_obaideh', 'cepage_petit_courbu', 'cepage_petit_manseng', 'cepage_petit_verdot', 'cepage_pineau_daunis', 'cepage_pinot_blanc', 'cepage_pinot_grigio', 'cepage_pinot_gris', 'cepage_pinot_noir', 'cepage_pinotage', 'cepage_piquepoul', 'cepage_poulsard', 'cepage_primitivo', 'cepage_riesling', 'cepage_rkatsiteli', 'cepage_romorantin', 'cepage_roussanne', 'cepage_sangiovese', 'cepage_saperavi', 'cepage_sauvignon_blanc', 'cepage_savagnin', 'cepage_sciaccarellu', 'cepage_semillon', 'cepage_shiraz', 'cepage_soave', 'cepage_sylvaner', 'cepage_syrah', 'cepage_tannat', 'cepage_tempranillo', 'cepage_terret', 'cepage_tibouren', 'cepage_torrontes', 'cepage_trebbiano', 'cepage_trousseau', 'cepage_ugni_blanc', 'cepage_vermentino', 'cepage_viognier', 'cepage_viura', 'cepage_xarel_lo', 'cepage_zinfandel', 'type_accessoire', 'type_effervescent', 'type_vin', 'couleur_blanc', 'couleur_rouge', 'couleur_rose', 'couleur_orange', 'couleur_ambre', 'couleur_rubis', 'prix_std', 'degres_std', 'pays_afrique_du_sud', 'pays_allemagne', 'pays_angleterre', 'pays_argentine', 'pays_armenie', 'pays_australie', 'pays_autriche', 'pays_bulgarie', 'pays_chili', 'pays_chine', 'pays_croatie', 'pays_espagne', 'pays_etats_unis', 'pays_france', 'pays_grece', 'pays_georgie', 'pays_hongrie', 'pays_italie', 'pays_liban', 'pays_maroc', 'pays_mexique', 'pays_moldavie', 'pays_nouvelle_zelande', 'pays_plateau_du_golan', 'pays_portugal', 'pays_perou', 'pays_roumanie', 'pays_slovenie', 'pays_suisse', 'pays_turquie', 'pays_uruguay', 'millesime_2024', 'millesime_2022', 'millesime_2023', 'millesime_2020', 'millesime_2019', 'millesime_2015', 'millesime_2021', 'millesime_2017', 'millesime_2016', 'millesime_2018', 'millesime_non millésimé', 'millesime_2010', 'millesime_2012', 'millesime_2014', 'millesime_1980', 'millesime_1998', 'millesime_2013', 'millesime_1959', 'millesime_1974', 'millesime_2001', 'millesime_2009', 'millesime_2008', 'millesime_1989', 'millesime_1969', 'millesime_2004', 'millesime_2007', 'millesime_2011', 'millesime_2003', 'millesime_2005', 'millesime_1979', 'millesime_2000', 'millesime_1995', 'bio_bool']

In [28]:
colonnes_objet = df.select_dtypes(include='object').columns
print(colonnes_objet)  # Pour voir la liste

Index(['nom', 'desc', 'accroche', 'visuel', 'producteur', 'pays', 'region',
       'appellation', 'cepages', 'millesime', 'accords', 'gout', 'caractere',
       'couleur', 'temp_serv', 'type_produit', 'bio', 'cepages_trouves'],
      dtype='object')

In [29]:
# 1. Assure-toi que 'bio_bool' existe
if 'bio_bool' not in df.columns:
    df['bio_bool'] = df['bio'].apply(lambda x: 1 if isinstance(x, str) and 'bio' in x.lower() else 0)

je garde dans df_num:

Toutes les colonnes numériques sauf deg_alcool,contennance  et prix,

Le nom du vin (nom),

Supprimer toutes les autres colonnes objet (texte, etc).

In [30]:
# 1. Colonnes objet
colonnes_objet = df.select_dtypes(include='object').columns

# 2. Conversion explicite en liste
colonnes_objet = list(colonnes_objet)

# 3. Colonnes numériques à supprimer
colonnes_num_a_supprimer = ['deg_alcool', 'prix', 'contenance']

# 4. On ajoute 'nom' à supprimer
colonnes_a_supprimer = colonnes_objet + colonnes_num_a_supprimer

# 5. Suppression dans le DataFrame (en ignorant les colonnes qui n'existent pas avec errors='ignore')
df_num = df.drop(columns=colonnes_a_supprimer, errors='ignore')

# 6. Vérification
print(df_num.info())
print(df_num.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4440 entries, 0 to 4439
Columns: 246 entries, Unnamed: 0 to bio_bool
dtypes: float64(2), int64(244)
memory usage: 8.3 MB
None
   Unnamed: 0  accord_aperitif  accord_barbecue  accord_champignon  \
0           0                1                0                  0
1           1                1                1                  1
2           2                1                0                  0
3           3                1                0                  0
4           4                1                1                  0

   accord_charcuterie  accord_charcuterie_corse  \
0                   0                         0
1                   1                         0
2                   0                         0
3                   0                         0
4                   0                         0

   accord_coquillage_et_crustace  accord_cuisine_du_monde  \
0                              0                        0
1                              0                        1
2                              0                        0
3                              1                        1
4                              0                        1

   accord_dessert_chocolate  accord_dessert_fruite  ...  millesime_1969  \
0                         0                      1  ...               0
1                         0                      0  ...               0
2                         0                      1  ...               0
3                         0                      1  ...               0
4                         0                      0  ...               0

   millesime_2004  millesime_2007  millesime_2011  millesime_2003  \
0               0               0               0               0
1               0               0               0               0
2               0               0               0               0
3               0               0               0               0
4               0               0               0               0

   millesime_2005  millesime_1979  millesime_2000  millesime_1995  bio_bool
0               0               0               0               0         0
1               0               0               0               0         0
2               0               0               0               0         0
3               0               0               0               0         0
4               0               0               0               0         0

[5 rows x 246 columns]

In [31]:
df_num.isna().sum()

Unnamed: 0            0
accord_aperitif       0
accord_barbecue       0
accord_champignon     0
accord_charcuterie    0
                     ..
millesime_2005        0
millesime_1979        0
millesime_2000        0
millesime_1995        0
bio_bool              0
Length: 246, dtype: int64

In [32]:
# Impression des colonnes objet

colonnes_objet = df.select_dtypes(include='object').columns.tolist()
print("Colonnes de type 'objet' (texte/catégoriel) :", colonnes_objet)

Colonnes de type 'objet' (texte/catégoriel) : ['nom', 'desc', 'accroche', 'visuel', 'producteur', 'pays', 'region', 'appellation', 'cepages', 'millesime', 'accords', 'gout', 'caractere', 'couleur', 'temp_serv', 'type_produit', 'bio', 'cepages_trouves']

In [33]:
from sklearn.neighbors import NearestNeighbors
import numpy as np
import pandas as pd

In [34]:
list(df_num.columns)

['Unnamed: 0',
 'accord_aperitif',
 'accord_barbecue',
 'accord_champignon',
 'accord_charcuterie',
 'accord_charcuterie_corse',
 'accord_coquillage_et_crustace',
 'accord_cuisine_du_monde',
 'accord_dessert_chocolate',
 'accord_dessert_fruite',
 'accord_digestif',
 'accord_entree',
 'accord_foie_gras',
 'accord_fromage',
 'accord_gambas_flambees',
 'accord_gibier',
 'accord_pave_de_turbot_cuit_au_beurre_sale_et_aux_salicornes',
 'accord_poisson',
 'accord_risotto_aux_asperges.',
 'accord_viande_blanche',
 'accord_viande_rouge',
 'accord_viandes_blanches',
 'accord_viandes_rouges',
 'accord_volaille',
 'accord_blanches',
 'accord_fromages.',
 'accord_gibiers',
 'accord_grillades',
 'accord_viandes',
 'accord_volailles',
 'caract_blanc_demi-sec',
 'caract_blanc_sec_ample_et_race',
 'caract_blanc_sec_leger_et_nerveux',
 'caract_blanc_sec_souple_et_fruite',
 'caract_blanc_sec_tres_aromatique',
 'caract_blanc_vin_de_maceration',
 'caract_floral',
 'caract_fruite_agrumes',
 'caract_fruite_fruits_blancs',
 'caract_mineral',
 'caract_orange_fruite_et_fin',
 "caract_rose_d'aperitif",
 'caract_rose_de_gastronomie',
 'caract_rose_de_repas',
 'caract_rouge_charnu_et_fruite',
 'caract_rouge_complexe',
 'caract_rouge_elegant_et_race',
 'caract_rouge_leger_et_fruite',
 'caract_rouge_puissant_et_genereux',
 'caract_rouge_tannique_et_race',
 'caract_vin_doux_naturel_et_de_liqueur',
 'caract_vin_effervescent',
 'caract_moelleux_et_liquoreux',
 'caract_tannique_et_race',
 'cepage_agiorgitiko',
 'cepage_aglianico',
 'cepage_albarino',
 'cepage_albariño',
 'cepage_aligote',
 'cepage_altesse',
 'cepage_arinto',
 'cepage_auxerrois',
 'cepage_baga',
 'cepage_barbera',
 'cepage_baroque',
 'cepage_bobal',
 'cepage_braucol',
 'cepage_cabernet_franc',
 'cepage_cabernet_sauvignon',
 'cepage_carcaghjolu',
 'cepage_carignan',
 'cepage_carmenere',
 'cepage_carricante',
 'cepage_chardonnay',
 'cepage_chasselas',
 'cepage_chenin',
 'cepage_chenin_blanc',
 'cepage_cinsault',
 'cepage_clairette',
 'cepage_colombard',
 'cepage_corvina',
 'cepage_corvinone',
 'cepage_counoise',
 'cepage_dolcetto',
 'cepage_falanghina',
 'cepage_fer_servadou',
 'cepage_fiano',
 'cepage_folle_blanche',
 'cepage_frappato',
 'cepage_furmint',
 'cepage_gamay',
 'cepage_garnacha',
 'cepage_gewurztraminer',
 'cepage_godello',
 'cepage_graciano',
 'cepage_greco',
 'cepage_grenache',
 'cepage_grillo',
 'cepage_grolleau',
 'cepage_gros_manseng',
 'cepage_gruner_veltliner',
 'cepage_hárslevelű',
 'cepage_inzolia',
 'cepage_jacquere',
 'cepage_lambrusco',
 'cepage_listán_negro',
 'cepage_loureira',
 'cepage_loureiro',
 'cepage_macabeo',
 'cepage_macabeu',
 'cepage_malbec',
 'cepage_malvasia',
 'cepage_marsanne',
 'cepage_mataro',
 'cepage_mauzac',
 'cepage_mazuelo',
 'cepage_melon_de_bourgogne',
 'cepage_mencia',
 'cepage_merlot',
 'cepage_monastrell',
 'cepage_mondeuse',
 'cepage_montepulciano',
 'cepage_moscato',
 'cepage_mourvedre',
 'cepage_muscat',
 'cepage_nebbiolo',
 'cepage_negroamaro',
 'cepage_nerello_mascalese',
 'cepage_nero_davola',
 'cepage_nielluccio',
 'cepage_niellucciu',
 'cepage_obaideh',
 'cepage_petit_courbu',
 'cepage_petit_manseng',
 'cepage_petit_verdot',
 'cepage_pineau_daunis',
 'cepage_pinot_blanc',
 'cepage_pinot_grigio',
 'cepage_pinot_gris',
 'cepage_pinot_noir',
 'cepage_pinotage',
 'cepage_piquepoul',
 'cepage_poulsard',
 'cepage_primitivo',
 'cepage_riesling',
 'cepage_rkatsiteli',
 'cepage_romorantin',
 'cepage_roussanne',
 'cepage_sangiovese',
 'cepage_saperavi',
 'cepage_sauvignon_blanc',
 'cepage_savagnin',
 'cepage_sciaccarellu',
 'cepage_semillon',
 'cepage_shiraz',
 'cepage_soave',
 'cepage_sylvaner',
 'cepage_syrah',
 'cepage_tannat',
 'cepage_tempranillo',
 'cepage_terret',
 'cepage_tibouren',
 'cepage_torrontes',
 'cepage_trebbiano',
 'cepage_trousseau',
 'cepage_ugni_blanc',
 'cepage_vermentino',
 'cepage_viognier',
 'cepage_viura',
 'cepage_xarel_lo',
 'cepage_zinfandel',
 'type_accessoire',
 'type_effervescent',
 'type_vin',
 'couleur_blanc',
 'couleur_rouge',
 'couleur_rose',
 'couleur_orange',
 'couleur_ambre',
 'couleur_rubis',
 'prix_std',
 'degres_std',
 'pays_afrique_du_sud',
 'pays_allemagne',
 'pays_angleterre',
 'pays_argentine',
 'pays_armenie',
 'pays_australie',
 'pays_autriche',
 'pays_bulgarie',
 'pays_chili',
 'pays_chine',
 'pays_croatie',
 'pays_espagne',
 'pays_etats_unis',
 'pays_france',
 'pays_grece',
 'pays_georgie',
 'pays_hongrie',
 'pays_italie',
 'pays_liban',
 'pays_maroc',
 'pays_mexique',
 'pays_moldavie',
 'pays_nouvelle_zelande',
 'pays_plateau_du_golan',
 'pays_portugal',
 'pays_perou',
 'pays_roumanie',
 'pays_slovenie',
 'pays_suisse',
 'pays_turquie',
 'pays_uruguay',
 'millesime_2024',
 'millesime_2022',
 'millesime_2023',
 'millesime_2020',
 'millesime_2019',
 'millesime_2015',
 'millesime_2021',
 'millesime_2017',
 'millesime_2016',
 'millesime_2018',
 'millesime_non millésimé',
 'millesime_2010',
 'millesime_2012',
 'millesime_2014',
 'millesime_1980',
 'millesime_1998',
 'millesime_2013',
 'millesime_1959',
 'millesime_1974',
 'millesime_2001',
 'millesime_2009',
 'millesime_2008',
 'millesime_1989',
 'millesime_1969',
 'millesime_2004',
 'millesime_2007',
 'millesime_2011',
 'millesime_2003',
 'millesime_2005',
 'millesime_1979',
 'millesime_2000',
 'millesime_1995',
 'bio_bool']

Explication
colonnes_racines : liste les “racines” de tes variables one-hot (ex : “couleur_”).

Pour chaque racine : on trouve la colonne one-hot activée pour le vin cible (celle qui vaut 1). On applique un poids fort juste sur cette colonne dans la distance.

Le reste a un poids de 1.

Le prix (colonne numérique), tu lui mets son poids séparément.

Résultat : le KNN va vraiment privilégier les vins de même couleur, même type, même pays…
C’est exactement ce que tu veux !

In [35]:
def recommander_vins_affichage_simple(
    df, 
    df_num, 
    vin_cible_nom, 
    colonnes_racines=('couleur_', 'type_', 'pays_','millesime_'),
    poids=(200, 200, 3, 200),
    colonne_prix='prix_std',
    poids_prix=100,
    n_voisins=5
):
    if vin_cible_nom not in df['nom'].values:
        raise ValueError(f"Vin '{vin_cible_nom}' non trouvé !")
    index_cible = df[df['nom'] == vin_cible_nom].index[0]

    colonnes_num = list(df_num.columns)
    poids_vect = np.ones(len(colonnes_num))
    for racine, p in zip(colonnes_racines, poids):
        for col in [col for col in colonnes_num if col.startswith(racine)]:
            poids_vect[colonnes_num.index(col)] = p
    if colonne_prix in colonnes_num:
        poids_vect[colonnes_num.index(colonne_prix)] = poids_prix

    vecteur_cible = df_num.iloc[index_cible].values.astype(float)
    mat = df_num.values.astype(float)
    distances = np.sqrt(np.sum(((mat - vecteur_cible) * poids_vect) ** 2, axis=1))
    distances[index_cible] = np.inf

    indices_voisins = np.argsort(distances)[:n_voisins-1]
    df_voisins = df.iloc[indices_voisins].copy()
    df_voisins['distance'] = distances[indices_voisins]

    df_bio = df[(df['bio_bool'] == 1) & (~df.index.isin(indices_voisins)) & (df.index != index_cible)]
    if not df_bio.empty:
        bios_num = df_num.loc[df_bio.index]
        bios_distances = np.sqrt(np.sum(((bios_num.values - vecteur_cible) * poids_vect) ** 2, axis=1))
        idx_min = np.argmin(bios_distances)
        vin_bio_index = df_bio.index[idx_min]
        df_voisins = pd.concat([df_voisins, df.loc[[vin_bio_index]].assign(distance=bios_distances[idx_min])])

    df_voisins = df_voisins.sort_values('distance')

    colonnes_clefs = [ 'nom', 'couleur', 'pays', 'bio_bool', 'type_produit', 'prix','distance']
    colonnes_clefs_cible = [col for col in colonnes_clefs if col != 'distance']
    cible = df.loc[[index_cible], colonnes_clefs_cible].copy()
    cible['distance'] = 0.0
    cible['nom'] = cible['nom'].values[0] + " (CIBLE)"

    def format_bio(val):
        return "O" if val == 1 else "N"
    cible['bio_bool'] = cible['bio_bool'].apply(format_bio)
    df_voisins['bio_bool'] = df_voisins['bio_bool'].apply(format_bio)

    final = pd.concat([cible, df_voisins[colonnes_clefs]], ignore_index=True)
    final = final[colonnes_clefs]

    print("\n=== RECOMMANDATIONS VIN (voisinage pondéré) ===")
    print(final.to_string(index=False))
    return final

In [36]:
vin_cible_nom = 'Sainte Croix - Rosé 2024'
result = recommander_vins_affichage_simple(df, df_num, vin_cible_nom)

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                     nom couleur   pays bio_bool type_produit  prix  distance
        Sainte Croix - Rosé 2024 (CIBLE)    Rosé France        N          Vin  7.95  0.000000
                  Studio by Miraval 2024    Rosé France        N          Vin 12.20  2.169265
         Miraflors 2024 - Domaine Lafage    Rosé France        N          Vin 13.50  2.864169
Les Pieds dans l'Eau 2024 - Alma Cersius    Rosé France        N          Vin  7.50  3.317817
       Gris Blanc 2024 - Gérard Bertrand    Rosé France        N          Vin 10.90  4.619525
   Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin 11.20 16.267265

df de recommandation

In [37]:
# DataFrame résultat vide
df_reco = pd.DataFrame(index=df['nom'], columns=['reco1', 'reco2', 'reco3', 'reco4'])

for vin_nom in df['nom']:
    try:
        # On prend 5 voisins (1 cible + 4 recos)
        result = recommander_vins_affichage_simple(df, df_num, vin_nom, n_voisins=5)
        noms_recos = result['nom'].tolist()[1:5]  # On saute la cible elle-même
        df_reco.loc[vin_nom] = noms_recos
    except Exception as e:
        df_reco.loc[vin_nom] = [None, None, None, None]

df_reco.index.name = 'vin_cible'

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                         nom couleur   pays bio_bool type_produit  prix   distance
Le Bal des Papillons 2024 - Horgelus (CIBLE)   Blanc France        N          Vin  8.60   0.000000
         Colombard-Sauvignon 2024 - Horgelus   Blanc France        N          Vin  6.60   2.892664
  N°3 - Colombard-Sauvignon Blanc 2024 - UBY   Blanc France        N          Vin  6.50   4.143947
    Gros-Manseng & Sauvignon 2024 - Horgelus   Blanc France        N          Vin  6.95  21.093868
 N°2 - Chardonnay - Chenin Blanc  2024 - UBY   Blanc France        N          Vin  7.90  34.106163
       Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin 11.20 284.057465

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                                nom couleur   pays bio_bool type_produit  prix   distance
   Lupo Meraviglia Tre di Tre 2022 - Botter (CIBLE)   Rouge Italie        N          Vin  10.9   0.000000
                     Château Moulin Bellegrave 2022   Rouge France        N          Vin  17.9  23.624684
                      Narassa 2022 - Domaine Lafage   Rouge France        N          Vin  16.5  37.382302
Crozes-Hermitage - Nobles Rives 2022 - Cave de Tain   Rouge France        N          Vin  17.9  41.362005
             Château Beaumont - Les Pierrières 2022   Rouge France        N          Vin   8.5  42.289907
                 Cuvée rouge 2022 - Château Salitis   Rouge France        O          Vin  11.0 169.071617

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                        nom couleur   pays bio_bool type_produit  prix   distance
Colombard-Sauvignon 2024 - Horgelus (CIBLE)   Blanc France        N          Vin  6.60   0.000000
       Le Bal des Papillons 2024 - Horgelus   Blanc France        N          Vin  8.60   2.892664
 N°3 - Colombard-Sauvignon Blanc 2024 - UBY   Blanc France        N          Vin  6.50   3.035064
   Gros-Manseng & Sauvignon 2024 - Horgelus   Blanc France        N          Vin  6.95  19.084444
N°2 - Chardonnay - Chenin Blanc  2024 - UBY   Blanc France        N          Vin  7.90  32.079059
      Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin 11.20 283.879777

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                               nom couleur   pays bio_bool type_produit  prix   distance
N°3 - Colombard-Sauvignon Blanc 2024 - UBY (CIBLE)   Blanc France        N          Vin  6.50   0.000000
               Colombard-Sauvignon 2024 - Horgelus   Blanc France        N          Vin  6.60   3.035064
              Le Bal des Papillons 2024 - Horgelus   Blanc France        N          Vin  8.60   4.143947
          Gros-Manseng & Sauvignon 2024 - Horgelus   Blanc France        N          Vin  6.95  18.216827
       N°2 - Chardonnay - Chenin Blanc  2024 - UBY   Blanc France        N          Vin  7.90  31.052984
             Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin 11.20 283.792605

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                               nom couleur   pays bio_bool type_produit  prix  distance
                      Rosé 2024 - Horgelus (CIBLE)    Rosé France        N          Vin   6.2  0.000000
                                    Dune Gris 2024    Rosé France        N          Vin   8.2  2.000292
Bandol - Les Adrets Rosé 2024 - Moulin de la Roque    Rosé France        N          Vin  13.2  4.277148
          Les Pieds dans l'Eau 2024 - Alma Cersius    Rosé France        N          Vin   7.5  4.462165
                   Miraflors 2024 - Domaine Lafage    Rosé France        N          Vin  13.5  5.824684
             Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin  11.2 22.155761

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                               nom couleur   pays bio_bool type_produit  prix  distance
                            Dune Gris 2024 (CIBLE)    Rosé France        N          Vin   8.2  0.000000
                              Rosé 2024 - Horgelus    Rosé France        N          Vin   6.2  2.000292
Bandol - Les Adrets Rosé 2024 - Moulin de la Roque    Rosé France        N          Vin  13.2  3.438262
          Les Pieds dans l'Eau 2024 - Alma Cersius    Rosé France        N          Vin   7.5  3.744215
                   Miraflors 2024 - Domaine Lafage    Rosé France        N          Vin  13.5  4.593200
             Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin  11.2 21.155681

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                                       nom couleur   pays bio_bool type_produit  prix  distance
Bandol - Les Adrets Rosé 2024 - Moulin de la Roque (CIBLE)    Rosé France        N          Vin  13.2  0.000000
                                            Dune Gris 2024    Rosé France        N          Vin   8.2  3.438262
                  Les Pieds dans l'Eau 2024 - Alma Cersius    Rosé France        N          Vin   7.5  4.014260
                                      Rosé 2024 - Horgelus    Rosé France        N          Vin   6.2  4.277148
                           Miraflors 2024 - Domaine Lafage    Rosé France        N          Vin  13.5  4.566005
                     Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin  11.2 20.282197

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                                       nom couleur    pays bio_bool type_produit  prix  distance
                     Les Darons 2023 - Jeff Carrel (CIBLE)   Rouge  France        N          Vin   8.5  0.000000
          Passo Del Sud Negroamaro Primitivo 2023 - Tagaro   Rouge  Italie        N          Vin   9.9 11.282189
       Brouilly - Les Clochers 2023 - Vignerons de Bel Air   Rouge  France        N          Vin  11.5 23.199063
    Bad Angel - Cabernet Sauvignon 2023 - Vignobles Vellas   Rouge  France        N          Vin   8.9 25.119838
                                 Ylirum 2023 - Vega Demara   Rouge Espagne        N          Vin   6.5 34.381060
Ventoux Bio - Le Vieux Clocher 2023 - Maison Arnoux & Fils   Rouge  France        O          Vin   9.9 47.053975

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                             nom couleur   pays bio_bool type_produit  prix  distance
Les Pieds dans l'Eau 2024 - Alma Cersius (CIBLE)    Rosé France        N          Vin  7.50  0.000000
                 Miraflors 2024 - Domaine Lafage    Rosé France        N          Vin 13.50  2.721495
                        Sainte Croix - Rosé 2024    Rosé France        N          Vin  7.95  3.317817
                                  Dune Gris 2024    Rosé France        N          Vin  8.20  3.744215
                          Studio by Miraval 2024    Rosé France        N          Vin 12.20  3.982846
           Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin 11.20 18.213898

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                               nom couleur   pays bio_bool type_produit  prix  distance
           Miraflors 2024 - Domaine Lafage (CIBLE)    Rosé France        N          Vin 13.50  0.000000
          Les Pieds dans l'Eau 2024 - Alma Cersius    Rosé France        N          Vin  7.50  2.721495
                          Sainte Croix - Rosé 2024    Rosé France        N          Vin  7.95  2.864169
                            Studio by Miraval 2024    Rosé France        N          Vin 12.20  3.326564
Bandol - Les Adrets Rosé 2024 - Moulin de la Roque    Rosé France        N          Vin 13.20  4.566005
             Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin 11.20 17.245808

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                     nom couleur   pays bio_bool type_produit  prix  distance
        Sainte Croix - Rosé 2024 (CIBLE)    Rosé France        N          Vin  7.95  0.000000
                  Studio by Miraval 2024    Rosé France        N          Vin 12.20  2.169265
         Miraflors 2024 - Domaine Lafage    Rosé France        N          Vin 13.50  2.864169
Les Pieds dans l'Eau 2024 - Alma Cersius    Rosé France        N          Vin  7.50  3.317817
       Gris Blanc 2024 - Gérard Bertrand    Rosé France        N          Vin 10.90  4.619525
   Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin 11.20 16.267265

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                     nom couleur   pays bio_bool type_produit  prix  distance
          Studio by Miraval 2024 (CIBLE)    Rosé France        N          Vin 12.20  0.000000
                Sainte Croix - Rosé 2024    Rosé France        N          Vin  7.95  2.169265
         Miraflors 2024 - Domaine Lafage    Rosé France        N          Vin 13.50  3.326564
       Gris Blanc 2024 - Gérard Bertrand    Rosé France        N          Vin 10.90  3.614696
Les Pieds dans l'Eau 2024 - Alma Cersius    Rosé France        N          Vin  7.50  3.982846
   Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin 11.20 15.174001

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                                        nom couleur   pays bio_bool type_produit  prix   distance
        Appassimento Wrap Around 2024 - Wrap Around (CIBLE)   Rouge Italie        N          Vin   8.5   0.000000
                       N°7 - Rouge Merlot-Tannat 2024 - UBY   Rouge France        N          Vin   6.5  84.175625
              Grenache Syrah 2024 - Marius by M. Chapoutier   Rouge France        N          Vin   7.9 109.118555
       Côtes du Rhone 2024 - Yannick Alleno & M. Chapoutier   Rouge France        N          Vin   9.9 115.101207
                      Belleruche Rouge 2024 - M. Chapoutier   Rouge France        N          Vin   9.2 170.070174
Côtes du Rhône 2024 - Sans Soufre Ajouté - Cave de Cairanne   Rouge France        O          Vin   9.5 251.054278

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                                                              nom couleur   pays bio_bool type_produit  prix   distance
                                        Morillon Blanc 2023 - Jeff Carrel (CIBLE)   Blanc France        N          Vin  11.5   0.000000
                                Chardonnay 2023 - Grande Réserve  - Maison Castel   Blanc France        N          Vin   6.9  18.111818
                                                Chardonnay Viognier 2023 - Auzias   Blanc France        N          Vin   9.0  22.115358
                                       Petit Chablis 2023 - Closerie des Alisiers   Blanc France        N          Vin  16.5  26.131930
Mâcon Villages 2023 - Domaine des Côteaux Val Lamartinien - Closerie des Alisiers   Blanc France        N          Vin  12.9  35.075459
          Viognier Sans Sulfites Ajoutés 2023 - Cuvée Secrète - Domaines Paul Mas   Blanc France        O          Vin  10.2 204.022737

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                                                       nom couleur   pays bio_bool type_produit  prix  distance
                                 Gris Blanc 2024 - Gérard Bertrand (CIBLE)    Rosé France        N          Vin  10.9  0.000000
Gourmandise 2024 -  Les Maitres Vignerons de la Presqu'île de Saint-Tropez    Rosé France        N          Vin   6.9  2.614641
                                       Moment de Plaisir 2024 - J.M Aujoux    Rosé France        N          Vin   8.5  3.350380
                                                    Studio by Miraval 2024    Rosé France        N          Vin  12.2  3.614696
                                    Diables & Co Rosé 2024 - MIP Diffusion    Rosé France        N          Vin   9.9  4.500032
                                     Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin  11.2 12.215348

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                                                               nom couleur   pays bio_bool type_produit  prix  distance
Gourmandise 2024 -  Les Maitres Vignerons de la Presqu'île de Saint-Tropez (CIBLE)    Rosé France        N          Vin   6.9  0.000000
                                                 Gris Blanc 2024 - Gérard Bertrand    Rosé France        N          Vin  10.9  2.614641
                                               Moment de Plaisir 2024 - J.M Aujoux    Rosé France        N          Vin   8.5  3.363219
                                            Diables & Co Rosé 2024 - MIP Diffusion    Rosé France        N          Vin   9.9  4.043715
                                                            Studio by Miraval 2024    Rosé France        N          Vin  12.2  4.930386
                                             Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin  11.2 11.389575

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                                                       nom couleur   pays bio_bool type_produit  prix  distance
                               Moment de Plaisir 2024 - J.M Aujoux (CIBLE)    Rosé France        N          Vin  8.50  0.000000
                                         Gris Blanc 2024 - Gérard Bertrand    Rosé France        N          Vin 10.90  3.350380
                                    Diables & Co Rosé 2024 - MIP Diffusion    Rosé France        N          Vin  9.90  3.359732
Gourmandise 2024 -  Les Maitres Vignerons de la Presqu'île de Saint-Tropez    Rosé France        N          Vin  6.90  3.363219
                                L'Été Gascon Rosé 2024 - Domaine Pellehaut    Rosé France        N          Vin  9.55  4.292158
                                     Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin 11.20 10.416143

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                                       nom couleur    pays bio_bool type_produit  prix  distance
  Passo Del Sud Negroamaro Primitivo 2023 - Tagaro (CIBLE)   Rouge  Italie        N          Vin   9.9  0.000000
                             Les Darons 2023 - Jeff Carrel   Rouge  France        N          Vin   8.5 11.282189
       Brouilly - Les Clochers 2023 - Vignerons de Bel Air   Rouge  France        N          Vin  11.5 13.939557
    Bad Angel - Cabernet Sauvignon 2023 - Vignobles Vellas   Rouge  France        N          Vin   8.9 15.882389
                                 Ylirum 2023 - Vega Demara   Rouge Espagne        N          Vin   6.5 24.500950
Ventoux Bio - Le Vieux Clocher 2023 - Maison Arnoux & Fils   Rouge  France        O          Vin   9.9 37.406032

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                                                       nom couleur   pays bio_bool type_produit  prix  distance
                            Diables & Co Rosé 2024 - MIP Diffusion (CIBLE)    Rosé France        N          Vin  9.90  0.000000
                                L'Été Gascon Rosé 2024 - Domaine Pellehaut    Rosé France        N          Vin  9.55  3.047183
                                       Moment de Plaisir 2024 - J.M Aujoux    Rosé France        N          Vin  8.50  3.359732
Gourmandise 2024 -  Les Maitres Vignerons de la Presqu'île de Saint-Tropez    Rosé France        N          Vin  6.90  4.043715
                                         Gris Blanc 2024 - Gérard Bertrand    Rosé France        N          Vin 10.90  4.500032
                                     Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin 11.20  8.310597

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                                                       nom couleur   pays bio_bool type_produit  prix  distance
                        L'Été Gascon Rosé 2024 - Domaine Pellehaut (CIBLE)    Rosé France        N          Vin  9.55  0.000000
                                    Diables & Co Rosé 2024 - MIP Diffusion    Rosé France        N          Vin  9.90  3.047183
                                                  Sunrose - Pays d'Oc 2024    Rosé France        N          Vin  6.50  4.025958
                                       Moment de Plaisir 2024 - J.M Aujoux    Rosé France        N          Vin  8.50  4.292158
Gourmandise 2024 -  Les Maitres Vignerons de la Presqu'île de Saint-Tropez    Rosé France        N          Vin  6.90  5.617376
                                     Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin 11.20  7.770901

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                                       nom couleur   pays bio_bool type_produit  prix   distance
                IGP Vaucluse Rouge - Xavier Vignon (CIBLE)   Rouge France        N          Vin   7.9   0.000000
                       Côtes du Rhône 2020 - Xavier Vignon   Rouge France        N          Vin  10.2 200.031042
                            Château Moulin Bellegrave 2022   Rouge France        N          Vin  17.9 200.062258
          Passo Del Sud Negroamaro Primitivo 2023 - Tagaro   Rouge Italie        N          Vin   9.9 200.092869
               Appassimento Wrap Around 2024 - Wrap Around   Rouge Italie        N          Vin   8.5 200.220442
Ventoux Bio - Le Vieux Clocher 2023 - Maison Arnoux & Fils   Rouge France        O          Vin   9.9 202.894967

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                             nom couleur   pays bio_bool type_produit  prix   distance
Gros-Manseng & Sauvignon 2024 - Horgelus (CIBLE)   Blanc France        N          Vin  6.95   0.000000
     N°2 - Chardonnay - Chenin Blanc  2024 - UBY   Blanc France        N          Vin  7.90  13.238069
        Le Pigeonnier Blanc 2024 - Cave de Pazac   Blanc France        N          Vin  8.50  15.295056
     L'Été Gascon Blanc 2024 - Domaine Pellehaut   Blanc France        N          Vin  9.55  16.191513
      N°3 - Colombard-Sauvignon Blanc 2024 - UBY   Blanc France        N          Vin  6.50  18.216827
           Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin 11.20 282.903783

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                       nom couleur   pays bio_bool type_produit  prix  distance
          Sunrose - Pays d'Oc 2024 (CIBLE)    Rosé France        N          Vin  6.50  0.000000
L'Été Gascon Rosé 2024 - Domaine Pellehaut    Rosé France        N          Vin  9.55  4.025958
                 Minuty Prestige Rosé 2024    Rosé France        N          Vin 18.30  4.825458
    Diables & Co Rosé 2024 - MIP Diffusion    Rosé France        N          Vin  9.90  5.035141
     Rosé 2024 - Domaine la Rose des Vents    Rosé France        O          Vin 11.20  5.173399
                  Watusi 2024 - Puech Haut    Rosé France        O          Vin 16.40 84.081355

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                                             nom couleur   pays bio_bool type_produit  prix   distance
                     Côtes du Rhône 2020 - Xavier Vignon (CIBLE)   Rouge France        N          Vin  10.2   0.000000
                                       Château de Saint-Pey 2020   Rouge France        N          Vin  22.5  27.205187
        IGP Vaucluse - Vieux Clocher 2020 - Maison Arnoux & Fils   Rouge France        N          Vin   6.9  37.017163
Montepulciano d'Abruzzo Riserva Terre della Brunda 2020 - Botter   Rouge Italie        N          Vin   8.3  50.249238
                  Côtes du Rhône - Richette 2020 - Patrick Lesec   Rouge France        N          Vin   9.9  60.000029
      Ventoux Bio - Le Vieux Clocher 2023 - Maison Arnoux & Fils   Rouge France        O          Vin   9.9 284.548772

=== RECOMMANDATIONS VIN (voisinage pondéré) ===
                                                nom couleur   pays bio_bool type_produit  prix   distance
             Château Moulin Bellegrave 2022 (CIBLE)   Rouge France        N          Vin  17.9   0.000000
                      Narassa 2022 - Domaine Lafage   Rouge France        N          Vin  16.5  14.315078
Crozes-Hermitage - Nobles Rives 2022 - Cave de Tain   Rouge France        N          Vin  17.9  18.161632
             Château Beaumont - Les Pierrières 2022   Rouge France        N          Vin   8.5  19.273097
                    Triplico Multiplo 2022 - Botter   Rouge Italie        N          Vin   9.5  23.595695
                 Cuvée rouge 2022 - Château Salitis   Rouge France        O          Vin  11.0 146.030340


In [38]:
df_reco

,reco1,reco2,reco3,reco4
vin_cible,,,,
Le Bal des Papillons 2024 - Horgelus,Colombard-Sauvignon 2024 - Horgelus,N°3 - Colombard-Sauvignon Blanc 2024 - UBY,Gros-Manseng & Sauvignon 2024 - Horgelus,N°2 - Chardonnay - Chenin Blanc 2024 - UBY
Lupo Meraviglia Tre di Tre 2022 - Botter,Château Moulin Bellegrave 2022,Narassa 2022 - Domaine Lafage,Crozes-Hermitage - Nobles Rives 2022 - Cave de...,Château Beaumont - Les Pierrières 2022
Colombard-Sauvignon 2024 - Horgelus,Le Bal des Papillons 2024 - Horgelus,N°3 - Colombard-Sauvignon Blanc 2024 - UBY,Gros-Manseng & Sauvignon 2024 - Horgelus,N°2 - Chardonnay - Chenin Blanc 2024 - UBY
N°3 - Colombard-Sauvignon Blanc 2024 - UBY,Colombard-Sauvignon 2024 - Horgelus,Le Bal des Papillons 2024 - Horgelus,Gros-Manseng & Sauvignon 2024 - Horgelus,N°2 - Chardonnay - Chenin Blanc 2024 - UBY
Rosé 2024 - Horgelus,Dune Gris 2024,Bandol - Les Adrets Rosé 2024 - Moulin de la R...,Les Pieds dans l'Eau 2024 - Alma Cersius,Miraflors 2024 - Domaine Lafage
...,...,...,...,...
L'Héritière des Pierres 2021 - Domaine Saint Sylvestre,Rouge 2021 - Domaine Saint Sylvestre,Karasi 2021 - Zorah,Gevrey Chambertin - Cuvée de Très Vieilles Vig...,Foradori 2021 - Foradori
Le Vallon 2022 - Domaine Milan,Vosne Romanée 2022 - Domaine Louis Fleurot,La Vialliere 2022 - Jean Michel Gerin,Volnay - Réserve Personnelle 2022 - Aegerter,Château Troplong Mondot 2022 - 1er Cru Classé B
Montlouis sur Loire - Les Bournais 2023 - Francois Chidaine,Faustine Blanc 2023 - Comte Abbatucci,Manon 2023 - Clos Marie,Ballade Pur Chenin 2023 - Vignobles Aguilem,Coudoulet de Beaucastel Blanc 2023 - Famille P...
La 50/50 2023 - Anne Gros et Jean-Paul Tollot,Saint Amour - Les Bambins 2023 - Les Bertrand,Amphora Rouge 2023 - Sans Sulfites Ajoutés - C...,Patrimonio 2023 - Domaine Ligenda,Artuke 2023 - Bodegas y Vinedos Artuke
La Vialliere 2022 - Jean Michel Gerin,Vosne Romanée 2022 - Domaine Louis Fleurot,Le Vallon 2022 - Domaine Milan,Château Troplong Mondot 2022 - 1er Cru Classé B,Volnay - Réserve Personnelle 2022 - Aegerter

In [39]:
df_reco.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4440 entries, Le Bal des Papillons 2024 - Horgelus to La Vialliere 2022 - Jean Michel Gerin
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   reco1   4440 non-null   object
 1   reco2   4440 non-null   object
 2   reco3   4440 non-null   object
 3   reco4   4440 non-null   object
dtypes: object(4)
memory usage: 302.5+ KB

In [40]:
colonnes_vin = [
    'nom', 'desc', 'accroche', 'visuel', 'producteur', 'contenance',
    'deg_alcool', 'pays', 'region', 'appellation','millesime',
    'accords', 'gout', 'caractere', 'couleur', 'temp_serv', 'type_produit',
    'bio', 'prix'
]

# On récupère la partie principale de df
df_infos = df[colonnes_vin].copy()

In [41]:
# Fusionner par le nom du vin (index de df_reco = nom du vin cible)
df_final_temp = df_infos.merge(
    df_reco,
    left_on='nom',
    right_index=True,
    how='left'  # ou 'inner' si tu veux seulement les vins pour lesquels tu as des recos
)

# Aperçu du résultat
print(df_final_temp.head())

                                          nom  \
0        Le Bal des Papillons 2024 - Horgelus
1    Lupo Meraviglia Tre di Tre 2022 - Botter
2         Colombard-Sauvignon 2024 - Horgelus
3  N°3 - Colombard-Sauvignon Blanc 2024 - UBY
4                        Rosé 2024 - Horgelus

                                                desc  \
0  Élaborée avec soin dans le respect des traditi...
1  Historiquement, la vinification dans les Pouil...
2  L'harmonieux mariage du colombard et du sauvig...
3  Léger et fruité ! Ce vin blanc aux arômes d'ag...
4  C'est un vin savoureux, séduisant à 100 . Frui...

                                            accroche  \
0  Plongez dans un univers de légèreté et délégan...
1  Une étoile montante des Pouilles vinifiée selo...
2  Savoureux mariage du colombard et du sauvignon...
3  La référence incontestable des Côtes de Gascog...
4  Découvrez un rosé des plus gourmands au rappor...

                                              visuel producteur  contenance  \
0  95769-fine_default/le-bal-des-papillons-2024-h...   Horgelus        0.75
1  80831-fine_default/lupo-meraviglia-tre-di-tre-...     Botter        0.75
2  94492-fine_default/colombard-sauvignon-2024-ho...   Horgelus        0.75
3  98180-fine_default/n3-colombard-sauvignon-blan...        UBY        0.75
4          95662-fine_default/rose-2024-horgelus.png   Horgelus        0.75

   deg_alcool    pays     region        appellation  ...  \
0        11.0  France  Sud-Ouest  Côtes de Gascogne  ...
1        14.5  Italie   Pouilles             Puglia  ...
2        11.5  France  Sud-Ouest  Côtes de Gascogne  ...
3        11.0  France  Sud-Ouest  Côtes de Gascogne  ...
4        11.5  France  Sud-Ouest  Côtes de Gascogne  ...

                               caractere couleur temp_serv type_produit  bio  \
0  Blanc Demi-sec, moelleux et liquoreux   Blanc    8-10°C          Vin  NaN
1                 Rouge Charnu et fruité   Rouge   16-18°C          Vin  NaN
2             Blanc Sec souple et fruité   Blanc      10°C          Vin  NaN
3                                    NaN   Blanc   10-12°C          Vin  NaN
4                        Rosé d'apéritif    Rosé      10°C          Vin  NaN

   prix                                 reco1  \
0   8.6   Colombard-Sauvignon 2024 - Horgelus
1  10.9        Château Moulin Bellegrave 2022
2   6.6  Le Bal des Papillons 2024 - Horgelus
3   6.5   Colombard-Sauvignon 2024 - Horgelus
4   6.2                        Dune Gris 2024

                                               reco2  \
0         N°3 - Colombard-Sauvignon Blanc 2024 - UBY
1                      Narassa 2022 - Domaine Lafage
2         N°3 - Colombard-Sauvignon Blanc 2024 - UBY
3               Le Bal des Papillons 2024 - Horgelus
4  Bandol - Les Adrets Rosé 2024 - Moulin de la R...

                                               reco3  \
0           Gros-Manseng & Sauvignon 2024 - Horgelus
1  Crozes-Hermitage - Nobles Rives 2022 - Cave de...
2           Gros-Manseng & Sauvignon 2024 - Horgelus
3           Gros-Manseng & Sauvignon 2024 - Horgelus
4           Les Pieds dans l'Eau 2024 - Alma Cersius

                                         reco4
0  N°2 - Chardonnay - Chenin Blanc  2024 - UBY
1       Château Beaumont - Les Pierrières 2022
2  N°2 - Chardonnay - Chenin Blanc  2024 - UBY
3  N°2 - Chardonnay - Chenin Blanc  2024 - UBY
4              Miraflors 2024 - Domaine Lafage

[5 rows x 23 columns]

In [47]:
nb_nan = df['couleur'].isna().sum()
print(f"Nombre de NaN dans la colonne 'couleur' : {nb_nan}")

Nombre de NaN dans la colonne 'couleur' : 3

In [44]:
df_final_temp.to_csv("base_vin_final_temps.csv")